#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRCSMS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CRCSMS")]
	public partial class CRCSMSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblOrderDetail(tblOrderDetail instance);
    partial void UpdatetblOrderDetail(tblOrderDetail instance);
    partial void DeletetblOrderDetail(tblOrderDetail instance);
    partial void InserttblMonthlyExp(tblMonthlyExp instance);
    partial void UpdatetblMonthlyExp(tblMonthlyExp instance);
    partial void DeletetblMonthlyExp(tblMonthlyExp instance);
    partial void InserttblExpProcess(tblExpProcess instance);
    partial void UpdatetblExpProcess(tblExpProcess instance);
    partial void DeletetblExpProcess(tblExpProcess instance);
    partial void InserttblOrder(tblOrder instance);
    partial void UpdatetblOrder(tblOrder instance);
    partial void DeletetblOrder(tblOrder instance);
    partial void InserttblProduct(tblProduct instance);
    partial void UpdatetblProduct(tblProduct instance);
    partial void DeletetblProduct(tblProduct instance);
    partial void InserttblProdStock(tblProdStock instance);
    partial void UpdatetblProdStock(tblProdStock instance);
    partial void DeletetblProdStock(tblProdStock instance);
    #endregion
		
		public CRCSMSDataContext() : 
				base(global::CRCSMS.Properties.Settings.Default.CRCSMSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CRCSMSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CRCSMSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CRCSMSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CRCSMSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblAdmin> tblAdmins
		{
			get
			{
				return this.GetTable<tblAdmin>();
			}
		}
		
		public System.Data.Linq.Table<tblOrderDetail> tblOrderDetails
		{
			get
			{
				return this.GetTable<tblOrderDetail>();
			}
		}
		
		public System.Data.Linq.Table<tblMonthlyExp> tblMonthlyExps
		{
			get
			{
				return this.GetTable<tblMonthlyExp>();
			}
		}
		
		public System.Data.Linq.Table<tblExpProcess> tblExpProcesses
		{
			get
			{
				return this.GetTable<tblExpProcess>();
			}
		}
		
		public System.Data.Linq.Table<tblOrder> tblOrders
		{
			get
			{
				return this.GetTable<tblOrder>();
			}
		}
		
		public System.Data.Linq.Table<tblProduct> tblProducts
		{
			get
			{
				return this.GetTable<tblProduct>();
			}
		}
		
		public System.Data.Linq.Table<tblProdStock> tblProdStocks
		{
			get
			{
				return this.GetTable<tblProdStock>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblAdmin")]
	public partial class tblAdmin
	{
		
		private int _adminID;
		
		private string _username;
		
		private string _password;
		
		private string _address;
		
		private string _mobile;
		
		private string _email;
		
		public tblAdmin()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adminID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int adminID
		{
			get
			{
				return this._adminID;
			}
			set
			{
				if ((this._adminID != value))
				{
					this._adminID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(50)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this._address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile", DbType="VarChar(50)")]
		public string mobile
		{
			get
			{
				return this._mobile;
			}
			set
			{
				if ((this._mobile != value))
				{
					this._mobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblOrderDetails")]
	public partial class tblOrderDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _orderDetailID;
		
		private System.Nullable<int> _orderID;
		
		private System.Nullable<int> _productID;
		
		private string _roastType;
		
		private string _groundType;
		
		private System.Nullable<int> _quantity;
		
		private System.Nullable<int> _productTotalPayment;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnorderDetailIDChanging(int value);
    partial void OnorderDetailIDChanged();
    partial void OnorderIDChanging(System.Nullable<int> value);
    partial void OnorderIDChanged();
    partial void OnproductIDChanging(System.Nullable<int> value);
    partial void OnproductIDChanged();
    partial void OnroastTypeChanging(string value);
    partial void OnroastTypeChanged();
    partial void OngroundTypeChanging(string value);
    partial void OngroundTypeChanged();
    partial void OnquantityChanging(System.Nullable<int> value);
    partial void OnquantityChanged();
    partial void OnproductTotalPaymentChanging(System.Nullable<int> value);
    partial void OnproductTotalPaymentChanged();
    #endregion
		
		public tblOrderDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orderDetailID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int orderDetailID
		{
			get
			{
				return this._orderDetailID;
			}
			set
			{
				if ((this._orderDetailID != value))
				{
					this.OnorderDetailIDChanging(value);
					this.SendPropertyChanging();
					this._orderDetailID = value;
					this.SendPropertyChanged("orderDetailID");
					this.OnorderDetailIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orderID", DbType="Int")]
		public System.Nullable<int> orderID
		{
			get
			{
				return this._orderID;
			}
			set
			{
				if ((this._orderID != value))
				{
					this.OnorderIDChanging(value);
					this.SendPropertyChanging();
					this._orderID = value;
					this.SendPropertyChanged("orderID");
					this.OnorderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productID", DbType="Int")]
		public System.Nullable<int> productID
		{
			get
			{
				return this._productID;
			}
			set
			{
				if ((this._productID != value))
				{
					this.OnproductIDChanging(value);
					this.SendPropertyChanging();
					this._productID = value;
					this.SendPropertyChanged("productID");
					this.OnproductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roastType", DbType="VarChar(50)")]
		public string roastType
		{
			get
			{
				return this._roastType;
			}
			set
			{
				if ((this._roastType != value))
				{
					this.OnroastTypeChanging(value);
					this.SendPropertyChanging();
					this._roastType = value;
					this.SendPropertyChanged("roastType");
					this.OnroastTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groundType", DbType="VarChar(50)")]
		public string groundType
		{
			get
			{
				return this._groundType;
			}
			set
			{
				if ((this._groundType != value))
				{
					this.OngroundTypeChanging(value);
					this.SendPropertyChanging();
					this._groundType = value;
					this.SendPropertyChanged("groundType");
					this.OngroundTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int")]
		public System.Nullable<int> quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productTotalPayment", DbType="Int")]
		public System.Nullable<int> productTotalPayment
		{
			get
			{
				return this._productTotalPayment;
			}
			set
			{
				if ((this._productTotalPayment != value))
				{
					this.OnproductTotalPaymentChanging(value);
					this.SendPropertyChanging();
					this._productTotalPayment = value;
					this.SendPropertyChanged("productTotalPayment");
					this.OnproductTotalPaymentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblMonthlyExp")]
	public partial class tblMonthlyExp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _monthExpID;
		
		private string _monthExpName;
		
		private string _monthlyBudget;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmonthExpIDChanging(int value);
    partial void OnmonthExpIDChanged();
    partial void OnmonthExpNameChanging(string value);
    partial void OnmonthExpNameChanged();
    partial void OnmonthlyBudgetChanging(string value);
    partial void OnmonthlyBudgetChanged();
    #endregion
		
		public tblMonthlyExp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monthExpID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int monthExpID
		{
			get
			{
				return this._monthExpID;
			}
			set
			{
				if ((this._monthExpID != value))
				{
					this.OnmonthExpIDChanging(value);
					this.SendPropertyChanging();
					this._monthExpID = value;
					this.SendPropertyChanged("monthExpID");
					this.OnmonthExpIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monthExpName", DbType="VarChar(50)")]
		public string monthExpName
		{
			get
			{
				return this._monthExpName;
			}
			set
			{
				if ((this._monthExpName != value))
				{
					this.OnmonthExpNameChanging(value);
					this.SendPropertyChanging();
					this._monthExpName = value;
					this.SendPropertyChanged("monthExpName");
					this.OnmonthExpNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monthlyBudget", DbType="VarChar(50)")]
		public string monthlyBudget
		{
			get
			{
				return this._monthlyBudget;
			}
			set
			{
				if ((this._monthlyBudget != value))
				{
					this.OnmonthlyBudgetChanging(value);
					this.SendPropertyChanging();
					this._monthlyBudget = value;
					this.SendPropertyChanged("monthlyBudget");
					this.OnmonthlyBudgetChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblExpProcess")]
	public partial class tblExpProcess : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _processID;
		
		private string _dateProcess;
		
		private string _coffeeBean;
		
		private string _priceCB;
		
		private string _totalexpCD;
		
		private string _worker;
		
		private string _salary;
		
		private string _totalSalary;
		
		private string _sticker;
		
		private string _priceSt;
		
		private string _totalexpSt;
		
		private string _gasTank;
		
		private string _priceGS;
		
		private string _totalexpGS;
		
		private string _aPU;
		
		private string _aPP;
		
		private string _aTotal;
		
		private string _bPU;
		
		private string _bPP;
		
		private string _bTotal;
		
		private string _cPU;
		
		private string _cPP;
		
		private string _cTotal;
		
		private string _totalexpProcess;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnprocessIDChanging(int value);
    partial void OnprocessIDChanged();
    partial void OndateProcessChanging(string value);
    partial void OndateProcessChanged();
    partial void OncoffeeBeanChanging(string value);
    partial void OncoffeeBeanChanged();
    partial void OnpriceCBChanging(string value);
    partial void OnpriceCBChanged();
    partial void OntotalexpCDChanging(string value);
    partial void OntotalexpCDChanged();
    partial void OnworkerChanging(string value);
    partial void OnworkerChanged();
    partial void OnsalaryChanging(string value);
    partial void OnsalaryChanged();
    partial void OntotalSalaryChanging(string value);
    partial void OntotalSalaryChanged();
    partial void OnstickerChanging(string value);
    partial void OnstickerChanged();
    partial void OnpriceStChanging(string value);
    partial void OnpriceStChanged();
    partial void OntotalexpStChanging(string value);
    partial void OntotalexpStChanged();
    partial void OngasTankChanging(string value);
    partial void OngasTankChanged();
    partial void OnpriceGSChanging(string value);
    partial void OnpriceGSChanged();
    partial void OntotalexpGSChanging(string value);
    partial void OntotalexpGSChanged();
    partial void OnaPUChanging(string value);
    partial void OnaPUChanged();
    partial void OnaPPChanging(string value);
    partial void OnaPPChanged();
    partial void OnaTotalChanging(string value);
    partial void OnaTotalChanged();
    partial void OnbPUChanging(string value);
    partial void OnbPUChanged();
    partial void OnbPPChanging(string value);
    partial void OnbPPChanged();
    partial void OnbTotalChanging(string value);
    partial void OnbTotalChanged();
    partial void OncPUChanging(string value);
    partial void OncPUChanged();
    partial void OncPPChanging(string value);
    partial void OncPPChanged();
    partial void OncTotalChanging(string value);
    partial void OncTotalChanged();
    partial void OntotalexpProcessChanging(string value);
    partial void OntotalexpProcessChanged();
    #endregion
		
		public tblExpProcess()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_processID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int processID
		{
			get
			{
				return this._processID;
			}
			set
			{
				if ((this._processID != value))
				{
					this.OnprocessIDChanging(value);
					this.SendPropertyChanging();
					this._processID = value;
					this.SendPropertyChanged("processID");
					this.OnprocessIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateProcess", DbType="VarChar(MAX)")]
		public string dateProcess
		{
			get
			{
				return this._dateProcess;
			}
			set
			{
				if ((this._dateProcess != value))
				{
					this.OndateProcessChanging(value);
					this.SendPropertyChanging();
					this._dateProcess = value;
					this.SendPropertyChanged("dateProcess");
					this.OndateProcessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_coffeeBean", DbType="VarChar(50)")]
		public string coffeeBean
		{
			get
			{
				return this._coffeeBean;
			}
			set
			{
				if ((this._coffeeBean != value))
				{
					this.OncoffeeBeanChanging(value);
					this.SendPropertyChanging();
					this._coffeeBean = value;
					this.SendPropertyChanged("coffeeBean");
					this.OncoffeeBeanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priceCB", DbType="VarChar(50)")]
		public string priceCB
		{
			get
			{
				return this._priceCB;
			}
			set
			{
				if ((this._priceCB != value))
				{
					this.OnpriceCBChanging(value);
					this.SendPropertyChanging();
					this._priceCB = value;
					this.SendPropertyChanged("priceCB");
					this.OnpriceCBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalexpCD", DbType="VarChar(50)")]
		public string totalexpCD
		{
			get
			{
				return this._totalexpCD;
			}
			set
			{
				if ((this._totalexpCD != value))
				{
					this.OntotalexpCDChanging(value);
					this.SendPropertyChanging();
					this._totalexpCD = value;
					this.SendPropertyChanged("totalexpCD");
					this.OntotalexpCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_worker", DbType="VarChar(50)")]
		public string worker
		{
			get
			{
				return this._worker;
			}
			set
			{
				if ((this._worker != value))
				{
					this.OnworkerChanging(value);
					this.SendPropertyChanging();
					this._worker = value;
					this.SendPropertyChanged("worker");
					this.OnworkerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salary", DbType="VarChar(50)")]
		public string salary
		{
			get
			{
				return this._salary;
			}
			set
			{
				if ((this._salary != value))
				{
					this.OnsalaryChanging(value);
					this.SendPropertyChanging();
					this._salary = value;
					this.SendPropertyChanged("salary");
					this.OnsalaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalSalary", DbType="VarChar(50)")]
		public string totalSalary
		{
			get
			{
				return this._totalSalary;
			}
			set
			{
				if ((this._totalSalary != value))
				{
					this.OntotalSalaryChanging(value);
					this.SendPropertyChanging();
					this._totalSalary = value;
					this.SendPropertyChanged("totalSalary");
					this.OntotalSalaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sticker", DbType="VarChar(50)")]
		public string sticker
		{
			get
			{
				return this._sticker;
			}
			set
			{
				if ((this._sticker != value))
				{
					this.OnstickerChanging(value);
					this.SendPropertyChanging();
					this._sticker = value;
					this.SendPropertyChanged("sticker");
					this.OnstickerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priceSt", DbType="VarChar(50)")]
		public string priceSt
		{
			get
			{
				return this._priceSt;
			}
			set
			{
				if ((this._priceSt != value))
				{
					this.OnpriceStChanging(value);
					this.SendPropertyChanging();
					this._priceSt = value;
					this.SendPropertyChanged("priceSt");
					this.OnpriceStChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalexpSt", DbType="VarChar(50)")]
		public string totalexpSt
		{
			get
			{
				return this._totalexpSt;
			}
			set
			{
				if ((this._totalexpSt != value))
				{
					this.OntotalexpStChanging(value);
					this.SendPropertyChanging();
					this._totalexpSt = value;
					this.SendPropertyChanged("totalexpSt");
					this.OntotalexpStChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gasTank", DbType="VarChar(50)")]
		public string gasTank
		{
			get
			{
				return this._gasTank;
			}
			set
			{
				if ((this._gasTank != value))
				{
					this.OngasTankChanging(value);
					this.SendPropertyChanging();
					this._gasTank = value;
					this.SendPropertyChanged("gasTank");
					this.OngasTankChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priceGS", DbType="VarChar(50)")]
		public string priceGS
		{
			get
			{
				return this._priceGS;
			}
			set
			{
				if ((this._priceGS != value))
				{
					this.OnpriceGSChanging(value);
					this.SendPropertyChanging();
					this._priceGS = value;
					this.SendPropertyChanged("priceGS");
					this.OnpriceGSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalexpGS", DbType="VarChar(50)")]
		public string totalexpGS
		{
			get
			{
				return this._totalexpGS;
			}
			set
			{
				if ((this._totalexpGS != value))
				{
					this.OntotalexpGSChanging(value);
					this.SendPropertyChanging();
					this._totalexpGS = value;
					this.SendPropertyChanged("totalexpGS");
					this.OntotalexpGSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aPU", DbType="NChar(10)")]
		public string aPU
		{
			get
			{
				return this._aPU;
			}
			set
			{
				if ((this._aPU != value))
				{
					this.OnaPUChanging(value);
					this.SendPropertyChanging();
					this._aPU = value;
					this.SendPropertyChanged("aPU");
					this.OnaPUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aPP", DbType="NChar(10)")]
		public string aPP
		{
			get
			{
				return this._aPP;
			}
			set
			{
				if ((this._aPP != value))
				{
					this.OnaPPChanging(value);
					this.SendPropertyChanging();
					this._aPP = value;
					this.SendPropertyChanged("aPP");
					this.OnaPPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aTotal", DbType="NChar(10)")]
		public string aTotal
		{
			get
			{
				return this._aTotal;
			}
			set
			{
				if ((this._aTotal != value))
				{
					this.OnaTotalChanging(value);
					this.SendPropertyChanging();
					this._aTotal = value;
					this.SendPropertyChanged("aTotal");
					this.OnaTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bPU", DbType="NChar(10)")]
		public string bPU
		{
			get
			{
				return this._bPU;
			}
			set
			{
				if ((this._bPU != value))
				{
					this.OnbPUChanging(value);
					this.SendPropertyChanging();
					this._bPU = value;
					this.SendPropertyChanged("bPU");
					this.OnbPUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bPP", DbType="NChar(10)")]
		public string bPP
		{
			get
			{
				return this._bPP;
			}
			set
			{
				if ((this._bPP != value))
				{
					this.OnbPPChanging(value);
					this.SendPropertyChanging();
					this._bPP = value;
					this.SendPropertyChanged("bPP");
					this.OnbPPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bTotal", DbType="NChar(10)")]
		public string bTotal
		{
			get
			{
				return this._bTotal;
			}
			set
			{
				if ((this._bTotal != value))
				{
					this.OnbTotalChanging(value);
					this.SendPropertyChanging();
					this._bTotal = value;
					this.SendPropertyChanged("bTotal");
					this.OnbTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cPU", DbType="NChar(10)")]
		public string cPU
		{
			get
			{
				return this._cPU;
			}
			set
			{
				if ((this._cPU != value))
				{
					this.OncPUChanging(value);
					this.SendPropertyChanging();
					this._cPU = value;
					this.SendPropertyChanged("cPU");
					this.OncPUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cPP", DbType="NChar(10)")]
		public string cPP
		{
			get
			{
				return this._cPP;
			}
			set
			{
				if ((this._cPP != value))
				{
					this.OncPPChanging(value);
					this.SendPropertyChanging();
					this._cPP = value;
					this.SendPropertyChanged("cPP");
					this.OncPPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cTotal", DbType="NChar(10)")]
		public string cTotal
		{
			get
			{
				return this._cTotal;
			}
			set
			{
				if ((this._cTotal != value))
				{
					this.OncTotalChanging(value);
					this.SendPropertyChanging();
					this._cTotal = value;
					this.SendPropertyChanged("cTotal");
					this.OncTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalexpProcess", DbType="VarChar(50)")]
		public string totalexpProcess
		{
			get
			{
				return this._totalexpProcess;
			}
			set
			{
				if ((this._totalexpProcess != value))
				{
					this.OntotalexpProcessChanging(value);
					this.SendPropertyChanging();
					this._totalexpProcess = value;
					this.SendPropertyChanged("totalexpProcess");
					this.OntotalexpProcessChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblOrders")]
	public partial class tblOrder : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _orderID;
		
		private string _name;
		
		private System.Nullable<System.DateTime> _dateOrdered;
		
		private System.Nullable<int> _orderTotalPayment;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnorderIDChanging(int value);
    partial void OnorderIDChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OndateOrderedChanging(System.Nullable<System.DateTime> value);
    partial void OndateOrderedChanged();
    partial void OnorderTotalPaymentChanging(System.Nullable<int> value);
    partial void OnorderTotalPaymentChanged();
    #endregion
		
		public tblOrder()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orderID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int orderID
		{
			get
			{
				return this._orderID;
			}
			set
			{
				if ((this._orderID != value))
				{
					this.OnorderIDChanging(value);
					this.SendPropertyChanging();
					this._orderID = value;
					this.SendPropertyChanged("orderID");
					this.OnorderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateOrdered", DbType="DateTime")]
		public System.Nullable<System.DateTime> dateOrdered
		{
			get
			{
				return this._dateOrdered;
			}
			set
			{
				if ((this._dateOrdered != value))
				{
					this.OndateOrderedChanging(value);
					this.SendPropertyChanging();
					this._dateOrdered = value;
					this.SendPropertyChanged("dateOrdered");
					this.OndateOrderedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orderTotalPayment", DbType="Int")]
		public System.Nullable<int> orderTotalPayment
		{
			get
			{
				return this._orderTotalPayment;
			}
			set
			{
				if ((this._orderTotalPayment != value))
				{
					this.OnorderTotalPaymentChanging(value);
					this.SendPropertyChanging();
					this._orderTotalPayment = value;
					this.SendPropertyChanged("orderTotalPayment");
					this.OnorderTotalPaymentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblProducts")]
	public partial class tblProduct : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _productID;
		
		private string _productName;
		
		private System.Nullable<int> _gram;
		
		private System.Nullable<int> _price;
		
		private System.Nullable<bool> _mediumRoast;
		
		private System.Nullable<bool> _darkRoast;
		
		private System.Nullable<bool> _wholeBeans;
		
		private System.Nullable<bool> _coarseGround;
		
		private System.Nullable<bool> _fineGround;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnproductIDChanging(int value);
    partial void OnproductIDChanged();
    partial void OnproductNameChanging(string value);
    partial void OnproductNameChanged();
    partial void OngramChanging(System.Nullable<int> value);
    partial void OngramChanged();
    partial void OnpriceChanging(System.Nullable<int> value);
    partial void OnpriceChanged();
    partial void OnmediumRoastChanging(System.Nullable<bool> value);
    partial void OnmediumRoastChanged();
    partial void OndarkRoastChanging(System.Nullable<bool> value);
    partial void OndarkRoastChanged();
    partial void OnwholeBeansChanging(System.Nullable<bool> value);
    partial void OnwholeBeansChanged();
    partial void OncoarseGroundChanging(System.Nullable<bool> value);
    partial void OncoarseGroundChanged();
    partial void OnfineGroundChanging(System.Nullable<bool> value);
    partial void OnfineGroundChanged();
    #endregion
		
		public tblProduct()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int productID
		{
			get
			{
				return this._productID;
			}
			set
			{
				if ((this._productID != value))
				{
					this.OnproductIDChanging(value);
					this.SendPropertyChanging();
					this._productID = value;
					this.SendPropertyChanged("productID");
					this.OnproductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productName", DbType="VarChar(50)")]
		public string productName
		{
			get
			{
				return this._productName;
			}
			set
			{
				if ((this._productName != value))
				{
					this.OnproductNameChanging(value);
					this.SendPropertyChanging();
					this._productName = value;
					this.SendPropertyChanged("productName");
					this.OnproductNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gram", DbType="Int")]
		public System.Nullable<int> gram
		{
			get
			{
				return this._gram;
			}
			set
			{
				if ((this._gram != value))
				{
					this.OngramChanging(value);
					this.SendPropertyChanging();
					this._gram = value;
					this.SendPropertyChanged("gram");
					this.OngramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int")]
		public System.Nullable<int> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mediumRoast", DbType="Bit")]
		public System.Nullable<bool> mediumRoast
		{
			get
			{
				return this._mediumRoast;
			}
			set
			{
				if ((this._mediumRoast != value))
				{
					this.OnmediumRoastChanging(value);
					this.SendPropertyChanging();
					this._mediumRoast = value;
					this.SendPropertyChanged("mediumRoast");
					this.OnmediumRoastChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_darkRoast", DbType="Bit")]
		public System.Nullable<bool> darkRoast
		{
			get
			{
				return this._darkRoast;
			}
			set
			{
				if ((this._darkRoast != value))
				{
					this.OndarkRoastChanging(value);
					this.SendPropertyChanging();
					this._darkRoast = value;
					this.SendPropertyChanged("darkRoast");
					this.OndarkRoastChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wholeBeans", DbType="Bit")]
		public System.Nullable<bool> wholeBeans
		{
			get
			{
				return this._wholeBeans;
			}
			set
			{
				if ((this._wholeBeans != value))
				{
					this.OnwholeBeansChanging(value);
					this.SendPropertyChanging();
					this._wholeBeans = value;
					this.SendPropertyChanged("wholeBeans");
					this.OnwholeBeansChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_coarseGround", DbType="Bit")]
		public System.Nullable<bool> coarseGround
		{
			get
			{
				return this._coarseGround;
			}
			set
			{
				if ((this._coarseGround != value))
				{
					this.OncoarseGroundChanging(value);
					this.SendPropertyChanging();
					this._coarseGround = value;
					this.SendPropertyChanged("coarseGround");
					this.OncoarseGroundChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fineGround", DbType="Bit")]
		public System.Nullable<bool> fineGround
		{
			get
			{
				return this._fineGround;
			}
			set
			{
				if ((this._fineGround != value))
				{
					this.OnfineGroundChanging(value);
					this.SendPropertyChanging();
					this._fineGround = value;
					this.SendPropertyChanged("fineGround");
					this.OnfineGroundChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblProdStocks")]
	public partial class tblProdStock : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _stockID;
		
		private System.Nullable<int> _productID;
		
		private string _date;
		
		private System.Nullable<int> _stocks;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnstockIDChanging(int value);
    partial void OnstockIDChanged();
    partial void OnproductIDChanging(System.Nullable<int> value);
    partial void OnproductIDChanged();
    partial void OndateChanging(string value);
    partial void OndateChanged();
    partial void OnstocksChanging(System.Nullable<int> value);
    partial void OnstocksChanged();
    #endregion
		
		public tblProdStock()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stockID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int stockID
		{
			get
			{
				return this._stockID;
			}
			set
			{
				if ((this._stockID != value))
				{
					this.OnstockIDChanging(value);
					this.SendPropertyChanging();
					this._stockID = value;
					this.SendPropertyChanged("stockID");
					this.OnstockIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productID", DbType="Int")]
		public System.Nullable<int> productID
		{
			get
			{
				return this._productID;
			}
			set
			{
				if ((this._productID != value))
				{
					this.OnproductIDChanging(value);
					this.SendPropertyChanging();
					this._productID = value;
					this.SendPropertyChanged("productID");
					this.OnproductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="VarChar(50)")]
		public string date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stocks", DbType="Int")]
		public System.Nullable<int> stocks
		{
			get
			{
				return this._stocks;
			}
			set
			{
				if ((this._stocks != value))
				{
					this.OnstocksChanging(value);
					this.SendPropertyChanging();
					this._stocks = value;
					this.SendPropertyChanged("stocks");
					this.OnstocksChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
